networks:
  morsegatonet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.2.0.0/16
      driver: default
services:
  master:
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch src/hos/server.launch"
    container_name: master
    networks:
      morsegatonet:
        ipv4_address: 10.2.0.5
  morse:
    build:
      context: ./docker
      dockerfile: Dockerfile.app
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && Xvfb -screen 0 100x100x24
      :2 & DISPLAY=:2 morse run morse_hospital_sim"
    container_name: morse
    depends_on:
    - master
    devices:
    - /dev/dri
    - /dev/snd
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=morse
    - ROS_MASTER_URI=http://master:11311
    - QT_X11_NO_MITSHM=1
    expose:
    - '8081'
    - '3000'
    - '3001'
    networks:
    - morsegatonet
    runtime: nvidia
    tty: true
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ./docker/hmrs_hostpital_simulation/morse_hospital_sim:/ros_ws/morse_hospital_sim
  motion_ctrl1:
    build:
      context: ./docker
      dockerfile: Dockerfile.motion
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch"
    container_name: motion_ctrl1
    depends_on:
    - master
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=motion_ctrl1
    - ROS_MASTER_URI=http://motion_ctrl1:11311
    - ROBOT_NAME=turtlebot1
    networks:
    - morsegatonet
    ports:
    - 9090:9090
    privileged: true
    runtime: runc
    tty: true
    volumes:
    - ./docker/motion_ctrl:/ros_ws/src/motion_ctrl/
    - ./docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/
  motion_ctrl2:
    build:
      context: ./docker
      dockerfile: Dockerfile.motion
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch"
    container_name: motion_ctrl2
    depends_on:
    - master
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=motion_ctrl2
    - ROS_MASTER_URI=http://motion_ctrl2:11311
    - ROBOT_NAME=turtlebot2
    networks:
    - morsegatonet
    ports:
    - 9090:9090
    privileged: true
    runtime: runc
    tty: true
    volumes:
    - ./docker/motion_ctrl:/ros_ws/src/motion_ctrl/
    - ./docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/
  motion_ctrl3:
    build:
      context: ./docker
      dockerfile: Dockerfile.motion
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch"
    container_name: motion_ctrl3
    depends_on:
    - master
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=motion_ctrl3
    - ROS_MASTER_URI=http://motion_ctrl3:11311
    - ROBOT_NAME=turtlebot3
    networks:
    - morsegatonet
    ports:
    - 9090:9090
    privileged: true
    runtime: runc
    tty: true
    volumes:
    - ./docker/motion_ctrl:/ros_ws/src/motion_ctrl/
    - ./docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/
  py_trees1:
    build:
      context: ./docker
      dockerfile: Dockerfile.pytrees
    container_name: py_trees1
    depends_on:
    - motion_ctrl1
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=py_trees1
    - ROS_MASTER_URI=http://motion_ctrl1:11311
    - ROBOT_NAME=turtlebot1
    - SKILLS=['approach_person', 'approach_robot', 'authenticate_person', 'deposit',
      'navigation', 'operate_drawer', 'pick_up']
    - 'ROBOT_CONFIG={"avg_speed": 0.8, "battery_consumption_rate": 0.0024000000000000002,
      "battery_level": 0.64, "id": 0, "local_plan": [["navigation", ["IC Room 1",
      [[-28.5, 18.0, -1.57], [-19, 16], [-37, 15], [-39.44, 33.98, 0.0]]]], ["approach_person",
      ["nurse"]], ["authenticate_person", ["nurse"]], ["operate_drawer", ["open"]],
      ["send_message", ["nurse"]], ["wait_message", ["r1"]], ["operate_drawer", ["close"]],
      ["navigation", ["Pharmacy", [[-39.44, 33.98, 0.0], [-37, 15], [-19, 16], [0,
      8], [-2, 2.6]]]], ["approach_robot", ["lab_arm"]], ["operate_drawer", ["open"]],
      ["send_message", ["lab_arm"]], ["wait_message", ["r1"]], ["operate_drawer",
      ["close"]]], "location": "PC Room 1", "position": [-28.5, 18.0, -1.57], "skills":
      ["approach_person", "approach_robot", "authenticate_person", "deposit", "navigation",
      "operate_drawer", "pick_up"]}'
    networks:
    - morsegatonet
    runtime: runc
    tty: true
    volumes:
    - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /var/run/dbus:/var/run/dbus:ro
    - /etc/machine-id:/etc/machine-id:ro
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ./docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/
  py_trees2:
    build:
      context: ./docker
      dockerfile: Dockerfile.pytrees
    container_name: py_trees2
    depends_on:
    - motion_ctrl2
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=py_trees2
    - ROS_MASTER_URI=http://motion_ctrl2:11311
    - ROBOT_NAME=turtlebot2
    - SKILLS=['approach_person', 'approach_robot', 'authenticate_person', 'deposit',
      'navigation', 'operate_drawer', 'pick_up']
    - 'ROBOT_CONFIG={"avg_speed": 0.8, "battery_consumption_rate": 0.0028, "battery_level":
      0.53, "id": 1, "local_plan": null, "location": "PC Room 7", "position": [-4,
      18, -1.57], "skills": ["approach_person", "approach_robot", "authenticate_person",
      "deposit", "navigation", "operate_drawer", "pick_up"]}'
    networks:
    - morsegatonet
    runtime: runc
    tty: true
    volumes:
    - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /var/run/dbus:/var/run/dbus:ro
    - /etc/machine-id:/etc/machine-id:ro
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ./docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/
  py_trees3:
    build:
      context: ./docker
      dockerfile: Dockerfile.pytrees
    container_name: py_trees3
    depends_on:
    - motion_ctrl3
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=py_trees3
    - ROS_MASTER_URI=http://motion_ctrl3:11311
    - ROBOT_NAME=turtlebot3
    - SKILLS=['approach_person', 'approach_robot', 'authenticate_person', 'deposit',
      'navigation', 'pick_up']
    - 'ROBOT_CONFIG={"avg_speed": 0.8, "battery_consumption_rate": 0.0013000000000000002,
      "battery_level": 0.45, "id": 2, "local_plan": null, "location": "PC Room 6",
      "position": [-11.5, 18, -1.57], "skills": ["approach_person", "approach_robot",
      "authenticate_person", "deposit", "navigation", "pick_up"]}'
    networks:
    - morsegatonet
    runtime: runc
    tty: true
    volumes:
    - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /var/run/dbus:/var/run/dbus:ro
    - /etc/machine-id:/etc/machine-id:ro
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ./docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/
  ros1_bridge:
    build:
      context: ./docker
      dockerfile: Dockerfile.pytrees
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && ros2 run ros1_bridge
      dynamic_bridge --bridge-all-topics "
    container_name: ros1_bridge
    depends_on:
    - master
    env_file:
    - /home/gastd/git/morse_simulation/sim.env
    environment:
    - ROS_HOSTNAME=ros1_bridge
    - ROS_MASTER_URI=http://master:11311
    networks:
    - morsegatonet
    runtime: runc
    tty: true
    volumes:
    - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /var/run/dbus:/var/run/dbus:ro
version: '2.3'
