networks:
  morsegatonet:
    driver: bridge
    ipam:
      config:
      - {subnet: 10.2.0.0/16}
      driver: default
services:
  master:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch src/motion_ctrl/launch/log.launch"
    container_name: master
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: ['ROBOTS_CONFIG=[{"avg_speed": 0.15, "battery_charge": 0.23995139509475963,
        "battery_discharge_rate": 0.00048000000000000007, "id": 1, "local_plan": null,
        "location": "PC Room 8", "position": [-11.5, 18.0, -1.57], "skills": ["approach_person",
        "authenticate_person", "navigation", "operate_drawer"]}, {"avg_speed": 0.15,
        "battery_charge": 0.634952869577942, "battery_discharge_rate": 0.00054, "id":
        2, "local_plan": null, "location": "PC Room 6", "position": [-19.0, 18.0,
        -1.57], "skills": ["approach_person", "approach_robot", "authenticate_person",
        "navigation", "operate_drawer"]}, {"avg_speed": 0.15, "battery_charge": 0.08039941318304296,
        "battery_discharge_rate": 0.00036, "id": 3, "local_plan": null, "location":
        "IC Room 2", "position": [-38.0, 21.5, 0.0], "skills": ["approach_person",
        "authenticate_person", "navigation", "operate_drawer"]}, {"avg_speed": 0.15,
        "battery_charge": 0.17496190705907763, "battery_discharge_rate": 0.0006000000000000001,
        "id": 4, "local_plan": [["navigation", ["IC Room 6", [[-39.44, 33.95, 0.0],
        [-37.0, 33.95], [-37.0, 18.93], [-33.9, 18.93, 3.14]]], "navto_room"], ["approach_person",
        ["nurse"], "approach_nurse"], ["authenticate_person", ["nurse"], "authenticate_nurse"],
        ["operate_drawer", ["open"], "open_drawer_nurse"], ["send_message", ["nurse"],
        "send_message"], ["wait_message", ["r1"], "wait_message"], ["operate_drawer",
        ["close"], "close_drawer_nurse"], ["navigation", ["Laboratory", [[-33.9, 18.93,
        3.14], [-37.0, 18.93], [-37.0, 16.0], [-26.0, 16.0], [-26.0, 13.0, 1.57]]],
        "navto_lab"], ["approach_robot", ["lab_arm"], "approach_arm"], ["operate_drawer",
        ["open"], "open_drawer_lab"], ["send_message", ["lab_arm"], "send_message"],
        ["wait_message", ["r1"], "wait_message"], ["operate_drawer", ["close"], "close_drawer_lab"]],
        "location": "IC Room 4", "position": [-39.44, 33.95, 0.0], "skills": ["approach_person",
        "approach_robot", "authenticate_person", "navigation", "operate_drawer"]},
        {"avg_speed": 0.15, "battery_charge": 0.7179616530181877, "battery_discharge_rate":
        0.0002, "id": 5, "local_plan": null, "location": "PC Room 7", "position":
        [-13.5, 18.0, -1.57], "skills": ["approach_robot", "authenticate_person",
        "navigation", "operate_drawer"]}, {"avg_speed": 0.15, "battery_charge": 0.5408465660492595,
        "battery_discharge_rate": 0.00072, "id": 6, "local_plan": null, "location":
        "IC Room 5", "position": [-32.88, 33.98, 3.14], "skills": ["approach_person",
        "authenticate_person", "navigation", "operate_drawer"]}]', 'NURSES_CONFIG=[{"location":
        "IC Room 6", "position": [-32.9, 19.93, 3.14]}]']
    networks:
      morsegatonet: {ipv4_address: 10.2.0.5}
    tty: true
    volumes: ['./log/:/root/.ros/logger_sim/', './docker/motion_ctrl:/ros_ws/src/motion_ctrl/']
  morse:
    build: {context: ./docker, dockerfile: Dockerfile.app}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && Xvfb -screen 0 100x100x24
      :1 & DISPLAY=:1 morse run morse_hospital_sim"
    container_name: morse
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=morse, 'ROS_MASTER_URI=http://master:11311', QT_X11_NO_MITSHM=1]
    expose: ['8081', '3000', '3001']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.X11-unix:/tmp/.X11-unix:rw', '~/.config/pulse/cookie:/root/.config/pulse/cookie',
      './docker/hmrs_hostpital_simulation/morse_hospital_sim:/ros_ws/morse_hospital_sim']
  motion_ctrl1:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl1
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl1, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot1]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  motion_ctrl2:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl2
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl2, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot2]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  motion_ctrl3:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl3
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl3, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot3]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  motion_ctrl4:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl4
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl4, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot4]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  motion_ctrl5:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl5
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl5, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot5]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  motion_ctrl6:
    build: {context: ./docker, dockerfile: Dockerfile.motion}
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch motion_ctrl
      base_navigation.launch --wait"
    container_name: motion_ctrl6
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=motion_ctrl6, 'ROS_MASTER_URI=http://master:11311',
      ROBOT_NAME=turtlebot6]
    networks: [morsegatonet]
    privileged: true
    runtime: runc
    tty: true
    volumes: ['./docker/motion_ctrl:/ros_ws/src/motion_ctrl/', './docker/turtlebot3_hospital_sim:/ros_ws/src/turtlebot3_hospital_sim/',
      './log/:/root/.ros/logger_sim/']
  py_trees1:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees1
    depends_on: [motion_ctrl1]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees1, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot1,
      'SKILLS=[''approach_person'', ''authenticate_person'', ''navigation'', ''operate_drawer'']',
      'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge": 0.23995139509475963, "battery_discharge_rate":
        0.00048000000000000007, "id": 1, "local_plan": null, "location": "PC Room
        8", "position": [-11.5, 18.0, -1.57], "skills": ["approach_person", "authenticate_person",
        "navigation", "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  py_trees2:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees2
    depends_on: [motion_ctrl2]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees2, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot2,
      'SKILLS=[''approach_person'', ''approach_robot'', ''authenticate_person'', ''navigation'',
        ''operate_drawer'']', 'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge":
        0.634952869577942, "battery_discharge_rate": 0.00054, "id": 2, "local_plan":
        null, "location": "PC Room 6", "position": [-19.0, 18.0, -1.57], "skills":
        ["approach_person", "approach_robot", "authenticate_person", "navigation",
        "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  py_trees3:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees3
    depends_on: [motion_ctrl3]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees3, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot3,
      'SKILLS=[''approach_person'', ''authenticate_person'', ''navigation'', ''operate_drawer'']',
      'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge": 0.08039941318304296, "battery_discharge_rate":
        0.00036, "id": 3, "local_plan": null, "location": "IC Room 2", "position":
        [-38.0, 21.5, 0.0], "skills": ["approach_person", "authenticate_person", "navigation",
        "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  py_trees4:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees4
    depends_on: [motion_ctrl4]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees4, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot4,
      'SKILLS=[''approach_person'', ''approach_robot'', ''authenticate_person'', ''navigation'',
        ''operate_drawer'']', 'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge":
        0.17496190705907763, "battery_discharge_rate": 0.0006000000000000001, "id":
        4, "local_plan": [["navigation", ["IC Room 6", [[-39.44, 33.95, 0.0], [-37.0,
        33.95], [-37.0, 18.93], [-33.9, 18.93, 3.14]]], "navto_room"], ["approach_person",
        ["nurse"], "approach_nurse"], ["authenticate_person", ["nurse"], "authenticate_nurse"],
        ["operate_drawer", ["open"], "open_drawer_nurse"], ["send_message", ["nurse"],
        "send_message"], ["wait_message", ["r1"], "wait_message"], ["operate_drawer",
        ["close"], "close_drawer_nurse"], ["navigation", ["Laboratory", [[-33.9, 18.93,
        3.14], [-37.0, 18.93], [-37.0, 16.0], [-26.0, 16.0], [-26.0, 13.0, 1.57]]],
        "navto_lab"], ["approach_robot", ["lab_arm"], "approach_arm"], ["operate_drawer",
        ["open"], "open_drawer_lab"], ["send_message", ["lab_arm"], "send_message"],
        ["wait_message", ["r1"], "wait_message"], ["operate_drawer", ["close"], "close_drawer_lab"]],
        "location": "IC Room 4", "position": [-39.44, 33.95, 0.0], "skills": ["approach_person",
        "approach_robot", "authenticate_person", "navigation", "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  py_trees5:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees5
    depends_on: [motion_ctrl5]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees5, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot5,
      'SKILLS=[''approach_robot'', ''authenticate_person'', ''navigation'', ''operate_drawer'']',
      'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge": 0.7179616530181877, "battery_discharge_rate":
        0.0002, "id": 5, "local_plan": null, "location": "PC Room 7", "position":
        [-13.5, 18.0, -1.57], "skills": ["approach_robot", "authenticate_person",
        "navigation", "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  py_trees6:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "colcon build && source /ros_ws/install/setup.bash && ros2
      launch py_trees_ros_behaviors tutorial_seven_docking_cancelling_failing_launch.py"
    container_name: py_trees6
    depends_on: [motion_ctrl6]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=py_trees6, 'ROS_MASTER_URI=http://master:11311', ROBOT_NAME=turtlebot6,
      'SKILLS=[''approach_person'', ''authenticate_person'', ''navigation'', ''operate_drawer'']',
      'ROBOT_CONFIG={"avg_speed": 0.15, "battery_charge": 0.5408465660492595, "battery_discharge_rate":
        0.00072, "id": 6, "local_plan": null, "location": "IC Room 5", "position":
        [-32.88, 33.98, 3.14], "skills": ["approach_person", "authenticate_person",
        "navigation", "operate_drawer"]}']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro', '/etc/machine-id:/etc/machine-id:ro', '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native',
      '~/.config/pulse/cookie:/root/.config/pulse/cookie', './docker/py_trees_ros_behaviors:/ros_ws/src/py_trees_ros_behaviors/']
  ros1_bridge:
    build: {context: ./docker, dockerfile: Dockerfile.pytrees}
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && ros2 run ros1_bridge
      dynamic_bridge --bridge-all-topics "
    container_name: ros1_bridge
    depends_on: [master]
    env_file: [/home/automni/git/morse_simulation/sim.env]
    environment: [ROS_HOSTNAME=ros1_bridge, 'ROS_MASTER_URI=http://master:11311']
    networks: [morsegatonet]
    runtime: runc
    tty: true
    volumes: ['/tmp/.docker.xauth:/tmp/.docker.xauth:rw', '/tmp/.X11-unix:/tmp/.X11-unix:rw',
      '/var/run/dbus:/var/run/dbus:ro']
version: '2.3'
