FROM amd64/ros:foxy-ros1-bridge-focal

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y ros-$ROS2_DISTRO-py-trees

WORKDIR /ros_ws

RUN mkdir -p /ros_ws/src
RUN cd /ros_ws/src
RUN /bin/bash -c "source /ros_entrypoint.sh && colcon build"
# COPY ros1_bridge /ros_ws/src/ros1_bridge
RUN echo "source /opt/ros/foxy/setup.bash" >> /root/.bashrc
# RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc
# RUN echo "source /ros_ws/install/setup.bash" >> /root/.bashrc
